window.ClaudeResponses = {
  default: "I can help you with that. Could you give me a bit more detail so I can give you the most useful response?",
  entries: [
    { keywords: ["facebook ads", "meta ads", "targeting"], response: "Great question. Meta targeting works best when you combine clear audience intent with a strong offer. Start with one goal per campaign so the algorithm learns faster and your data stays clean.\n\nA simple structure to begin with is:\n- 1 campaign objective\n- 2 to 3 ad sets (different audience angles)\n- 2 creatives per ad set\n\nThen review results after 3-5 days, cut poor performers, and scale only what is profitable. Keep creative testing continuous because even perfect targeting eventually fatigues." },
    { keywords: ["landing page"], response: "A high-converting landing page is mostly about message clarity. Above the fold, your visitor should immediately understand who the offer is for and what result they get.\n\nUse this sequence:\n- Strong outcome headline\n- One-line supporting subheadline\n- Social proof block\n- Clear call-to-action\n\nIf your conversion rate is low, simplify first. Remove sections that do not directly help trust, clarity, or objection handling." },
    { keywords: ["headline", "copywriting"], response: "Your headline should promise a specific outcome in plain language. Avoid clever wording if it reduces clarity.\n\nA reliable framework is:\n- Desired result\n- Time frame or effort level\n- Audience qualifier\n\nExample style: \"Get qualified leads in 14 days without hiring a full sales team.\" Then support it with proof right below the headline." },
    { keywords: ["portfolio", "github", "projects"], response: "Your portfolio should demonstrate outcomes, not just code screenshots. Recruiters and clients care about what problem you solved and why your decisions mattered.\n\nFor each project include:\n- Problem statement\n- Your technical approach\n- Measurable result\n\nPin your best three repositories on GitHub and write clear READMEs. Quality beats quantity when people scan your work quickly." },
    { keywords: ["pricing", "clients", "retainer"], response: "Pricing becomes easier when your offer is packaged around outcomes instead of hourly effort. Clients pay faster when they can connect your work to revenue, leads, or time saved.\n\nYou can position retainers with:\n- Defined monthly deliverables\n- Clear success metrics\n- A communication cadence\n\nStart with one core package, then add optional upgrades. Too many pricing choices can slow down decisions." },
    { keywords: ["nigeria", "african market"], response: "In Nigeria and broader African markets, trust and proof are often more important than aggressive claims. Local context, payment flexibility, and WhatsApp-friendly funnels can improve conversion significantly.\n\nFocus on:\n- Mobile-first pages\n- Fast load times on weaker networks\n- Local testimonials and case studies\n\nIf your audience is mixed across regions, segment your campaigns by country and adjust copy to local language patterns." },
    { keywords: ["javascript"], response: "If you want to improve in JavaScript quickly, build small features repeatedly and review your own code structure. Consistency matters more than cramming advanced topics too early.\n\nA practical path is:\n- Master functions, arrays, objects, async/await\n- Build mini apps with DOM manipulation\n- Refactor each project once for readability\n\nDocument what you learn after every project. That reflection step helps you level up much faster." },
    { keywords: ["css"], response: "Great CSS comes from layout discipline and predictable spacing systems. Start mobile-first, define reusable spacing tokens, and avoid one-off overrides whenever possible.\n\nI recommend this habit:\n- Build from smallest viewport first\n- Scale up with min-width media queries\n- Keep component styles isolated\n\nWhen layouts break, inspect overflow and width constraints first. Most issues are caused by fixed widths or unwrapped content." },
    { keywords: ["html"], response: "Strong HTML improves accessibility, SEO, and maintainability at the same time. Semantic structure also makes styling and scripting much cleaner.\n\nUse semantic elements intentionally:\n- `header`, `main`, `section`, `nav`, `button`\n- Labels for form fields\n- Proper heading hierarchy\n\nWhen in doubt, prioritize meaningful structure before visual styling. It reduces technical debt later." },
    { keywords: ["code"], response: "When writing code, optimize first for clarity, then performance. Teams move faster when files are predictable and naming is consistent.\n\nA useful checklist is:\n- Small functions with single responsibility\n- Descriptive names over short names\n- Comments only where reasoning is non-obvious\n\nIf you are debugging frequently, add lightweight logs and isolate state changes. That usually reveals the issue quickly." },
    { keywords: ["email", "cold outreach"], response: "Cold email works when it feels relevant, short, and credible. Most people over-explain and lose attention in the first two lines.\n\nTry this format:\n- Personalized opener\n- One specific value proposition\n- Low-friction call-to-action\n\nKeep it under 120 words and test subject lines in small batches. Small improvements in reply rate create huge pipeline gains." },
    { keywords: ["youtube", "video"], response: "If you are growing through YouTube, clarity and consistency beat production quality early on. Focus on one niche problem your audience cares about.\n\nA practical content system:\n- 3 core topics repeated from different angles\n- Hook in first 10 seconds\n- Strong CTA at the end\n\nReview retention analytics weekly and tighten intros. Better retention usually improves recommendations automatically." },
    { keywords: ["morning"], response: "Good morning. Starting with a short, focused plan can make the entire day more productive. Pick one meaningful output and protect deep work time for it.\n\nYou could start with:\n- 60-90 minutes of distraction-free execution\n- A short outreach or growth task\n- A quick review of key metrics\n\nIf you want, I can help you plan your top three priorities for today based on your current goals." },
    { keywords: ["hello", "hi"], response: "Hi there. I can help you think through strategy, improve writing, and solve technical implementation steps in a clear way.\n\nCommon ways I can support you:\n- Business and marketing ideas\n- Portfolio and career direction\n- Frontend coding help\n\nShare what you are working on right now, and I will help you map the fastest next step." },
    { keywords: ["help", "what can you do"], response: "I can support you across execution and planning, especially for business growth and frontend work. I aim to be practical and direct so you can act quickly.\n\nI can help with:\n- Messaging, offers, and client acquisition\n- Landing pages, copy, and conversion ideas\n- HTML, CSS, JavaScript implementation guidance\n\nTell me your current challenge and I will break it into a clear action plan you can use immediately." },
    { keywords: ["react"], response: "React projects stay maintainable when component boundaries are clear and state is placed intentionally. Keep state close to where it is used unless multiple branches need it.\n\nA reliable pattern:\n- Presentational components for UI only\n- Container components for data flow\n- Shared hooks for repeated logic\n\nWhen performance drops, profile re-renders before premature optimization. Memoization should solve a measured problem." },
    { keywords: ["seo"], response: "SEO improves fastest when content matches search intent and pages are technically clean. You need both relevance and crawlability.\n\nPrioritize:\n- Search-intent aligned page titles and headings\n- Internal linking to related pages\n- Fast page speed and mobile usability\n\nCreate pages that answer one primary query deeply. Broad, generic pages usually underperform in competitive niches." },
    { keywords: ["sales"], response: "Sales improves when your message connects directly to pain, impact, and urgency. Most offers fail because the value is described too vaguely.\n\nIn calls or messages, focus on:\n- Current pain and cost of inaction\n- Desired future outcome\n- Clear next-step commitment\n\nUse simple language and confirm understanding often. Clarity increases trust and close rates." },
    { keywords: ["agency"], response: "Running an agency gets easier when delivery is standardized. Productized services reduce chaos and make hiring or delegation much simpler.\n\nStart by defining:\n- One ideal client profile\n- One core offer with fixed process\n- One reporting format clients understand quickly\n\nAs demand grows, document your workflow in checklists. That turns your agency into a repeatable system instead of a hustle loop." },
    { keywords: ["design"], response: "Good design decisions come from hierarchy, spacing, and contrast before decoration. If users cannot scan quickly, the interface feels harder than it should.\n\nUse this order:\n- Establish content priority\n- Build consistent spacing scale\n- Apply color and visual accents last\n\nWhen in doubt, remove visual noise. Simpler interfaces usually perform better in real-world use." }
  ]
};
